export default {
	state:{
		footer_nav:[
			{
				name:'小视频',
				name_code:'smallVideo',
				icon:require('@/assets/tabImg/2019_a030_7.png'),
				select_icon:require('@/assets/tabImg/2019_a030_8.png'),
                path_url:"/pages/smallVideo/smallVideo",
				size:'small',
				path:"/smallVideo"
			},
			{
				name:'短视频',
				name_code:'shortVideo',
				icon:require('@/assets/tabImg/2019_a030_9.png'),
				select_icon:require('@/assets/tabImg/2019_a030_10.png'),
                path_url:"/pages/shortVideo/shortVideo",
				size:'small',
				path:"/shortVideo"
			},
		{
			name:'发布',
			name_code:'publish',
			icon:require('@/assets/tabImg/2019_a030_15.png'),
			select_icon:require('@/assets/tabImg/2019_a030_16.png'),
            path_url:"/pages/publish/publish",
			size:'big',
			path:"/publish"
		},
    {
    	name:'直播',
    	name_code:'live',
    	icon:require('@/assets/tabImg/2019_a030_11.png'),
    	select_icon:require('@/assets/tabImg/2019_a030_12.png'),
        path_url:"/pages/live/live",
		size:'small',
		path:"/live"
    },
    {
    	name:'我的',
    	name_code:'me',
    	icon:require('@/assets/tabImg/2019_a030_13.png'),
    	select_icon:require('@/assets/tabImg/2019_a030_14.png'),
        path_url:"/pages/me/me",
		size:'small',
		path:"/me"
    }	
		],
		now_page_path:"/smallVideo",
	},
	mutations:{
		change_nav_list(state,data){
			state.footer_nav = data;
		},
		change_page(state,path){
			state.now_page_path = path;
		}
	},
	actions:{
		
	}
}